sample_id: "HG008"
bam: "HG008_example_data/HG008.Revio.hifi_reads.subsampled.bam"
methylation_dir: "HG008_cpg_methylation/"
copy_number: "HG008_example_data/HG008_sample_cn.tsv"
variants: "HG008_example_data/HG008_variants.tsv"
haplotags: "HG008_example_data/HG008_haplotags.tsv"
haploblocks: "HG008_example_data/HG008_haploblocks.tsv"
snv_clusters: "HG008_example_data/HG008_clusters.tsv"
snv_cluster_assignments: "HG008_example_data/HG008_snv_cluster_assignments.tsv"
output_dir: "processed_training_data/"
